
CPPUNIT_TEST_SUITE_REGISTRATION( test_problem_4_findMedianSortedArrays );
CPPUNIT_TEST_SUITE_REGISTRATION( test_problem_10_isMatch );
CPPUNIT_TEST_SUITE_REGISTRATION( test_problem_26_removeDuplicates );
CPPUNIT_TEST_SUITE_REGISTRATION( test_problem_36_isValidSudoku );
CPPUNIT_TEST_SUITE_REGISTRATION( test_problem_37_solveSudoku );
CPPUNIT_TEST_SUITE_REGISTRATION( test_problem_53_maxSubArray );